# This is the name of the workflow
name: Node.js CI

# When should this run?
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# What jobs should the robot do?
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test on Node 18 and 20

    steps:
      - uses: actions/checkout@v3 # Step 1: Download the code

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # Step 2: Install Node on the robot
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci # Step 3: Clean install of packages

      - name: Build/Test
        run: |
          npm run build --if-present
          # We don't have tests yet, but if we did, they would run here:
          # npm test
